### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by munikarmanish** [Saruspete/LinuxNetworking#1]
I looked at the slides in SlideShare. They were very interesting. They brought me here but it seems that there's no progress in this repository since 2 years ago. Is this project halted now?

If yes, are there any other good sources of good documentation and explanation of the Linux kernel network stack? I'm working on customizing container overlay networks and finding it hard to comprehend the logic directly from the source code. 

Thanks!

**Comment by Saruspete** [comment]
Greetings,

Not dead, but on hold as I need to create a draw.io plugin to ease the integration of the diagrams with kernel sources and versions. This diagram is based on 4.14, but with XDP, eBPF and other features, I wanted to lay better foundations before going further, to avoid forking the graph for newer versions and features

Didn't had the time to work on it for a while, but I'll go back on this soon.

Regarding the "container overlay", do you mean namespaces? 
Didn't look deeply on it wet, but it seems to be handled in `net/core/net_namespace.c`, with init & netlink registration done by `net_ns_init() :: rtnl_register()`, to handle messages `RTM_NEWNSID` and `RTM_GETNSID` (called by userspace `ip netns` functions).

Upon creation of new device, many `register_pernet_*` are called, which register them on the default namespace.

I didn't figure out yet how/where the namespace is handled during the packet reception.

Cheers

**Comment by munikarmanish** [comment]
Thanks for the response!

No, I'm not worried about namespaces at the moment (maybe later).

What I'm trying to do is trace the journey of an overlay packet through the kernel network stack to find out how it passes from one device to another (such as eth0 → vxlan0 → docker0 → veth0...) and which part consumes the most CPU/time. There are multiple softirqs involved so it's quite difficult to even follow the function calls, let alone analyze their overhead.

**Comment by Saruspete** [comment]
If you want to trace the kernel internals, you should have a look at ftrace (the official kernel tracer), and its frontend `trace-cmd`. So you can try something like:
```
# Trace the whole kernel:
trace-cmd record -p function_graph -e net sleep 10
# Or trace a single process
trace-cmd record -p function_graph -e net -P $pid
```
These record will generate a trace.dat file, which you can now parse with: `trace-cmd report` or `trace-cmd hist` and other features of trace-cmd. 


From my schema, the transfer of skb between devices seems to be done by `net/core/dev.c :: __netif_receive_skb_core()`, with
```
rx_handler = rcu_dereference(skb->dev->rx_handler);
```

Where all device has to register itself using `netdev_rx_handler_register`:
- `drivers/net/team/team.c :: team_port_add()`
- `drivers/net/bonding/bond_main.c :: bond_enslave()`
- `net/bridge/br_if.c :: br_add_if()`
- `drivers/net/ipvlan/ipvtap.c :: ip_ipvtap_newlink()`
- `drivers/net/macsec.c :: register_macsec_dev()`
- `drivers/net/macvtap.c :: macvtap_newlink()`
- `drivers/net/macvlan.c :: macvlan_port_create()`

**Comment by Saruspete** [comment]
Cleanup :)
